// Generated by gencpp from file node_manager/EnvExecuteResponse.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_ENVEXECUTERESPONSE_H
#define NODE_MANAGER_MESSAGE_ENVEXECUTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <node_manager/Properties.h>

namespace node_manager
{
template <class ContainerAllocator>
struct EnvExecuteResponse_
{
  typedef EnvExecuteResponse_<ContainerAllocator> Type;

  EnvExecuteResponse_()
    : properties()  {
    }
  EnvExecuteResponse_(const ContainerAllocator& _alloc)
    : properties(_alloc)  {
  (void)_alloc;
    }



   typedef  ::node_manager::Properties_<ContainerAllocator>  _properties_type;
  _properties_type properties;




  typedef boost::shared_ptr< ::node_manager::EnvExecuteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::EnvExecuteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnvExecuteResponse_

typedef ::node_manager::EnvExecuteResponse_<std::allocator<void> > EnvExecuteResponse;

typedef boost::shared_ptr< ::node_manager::EnvExecuteResponse > EnvExecuteResponsePtr;
typedef boost::shared_ptr< ::node_manager::EnvExecuteResponse const> EnvExecuteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::EnvExecuteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_manager': ['/home/artsobes/Documents/Development/ROS/catkin_ws/src/node_manager/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::EnvExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::EnvExecuteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::EnvExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a585643b7376f76d182f9c4487be9be";
  }

  static const char* value(const ::node_manager::EnvExecuteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a585643b7376f76ULL;
  static const uint64_t static_value2 = 0xd182f9c4487be9beULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/EnvExecuteResponse";
  }

  static const char* value(const ::node_manager::EnvExecuteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Properties properties\n\
\n\
\n\
================================================================================\n\
MSG: node_manager/Properties\n\
Position position\n\
float32 radius\n\
string type\n\
\n\
================================================================================\n\
MSG: node_manager/Position\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::node_manager::EnvExecuteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.properties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EnvExecuteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::EnvExecuteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::EnvExecuteResponse_<ContainerAllocator>& v)
  {
    s << indent << "properties: ";
    s << std::endl;
    Printer< ::node_manager::Properties_<ContainerAllocator> >::stream(s, indent + "  ", v.properties);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_ENVEXECUTERESPONSE_H
