// Generated by gencpp from file node_manager/EnvExecute.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_ENVEXECUTE_H
#define NODE_MANAGER_MESSAGE_ENVEXECUTE_H

#include <ros/service_traits.h>


#include <node_manager/EnvExecuteRequest.h>
#include <node_manager/EnvExecuteResponse.h>


namespace node_manager
{

struct EnvExecute
{

typedef EnvExecuteRequest Request;
typedef EnvExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnvExecute
} // namespace node_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_manager::EnvExecute > {
  static const char* value()
  {
    return "57894eb0b15cbedc08e6487c6e2e5c4d";
  }

  static const char* value(const ::node_manager::EnvExecute&) { return value(); }
};

template<>
struct DataType< ::node_manager::EnvExecute > {
  static const char* value()
  {
    return "node_manager/EnvExecute";
  }

  static const char* value(const ::node_manager::EnvExecute&) { return value(); }
};


// service_traits::MD5Sum< ::node_manager::EnvExecuteRequest> should match 
// service_traits::MD5Sum< ::node_manager::EnvExecute > 
template<>
struct MD5Sum< ::node_manager::EnvExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::EnvExecute >::value();
  }
  static const char* value(const ::node_manager::EnvExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::EnvExecuteRequest> should match 
// service_traits::DataType< ::node_manager::EnvExecute > 
template<>
struct DataType< ::node_manager::EnvExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::node_manager::EnvExecute >::value();
  }
  static const char* value(const ::node_manager::EnvExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_manager::EnvExecuteResponse> should match 
// service_traits::MD5Sum< ::node_manager::EnvExecute > 
template<>
struct MD5Sum< ::node_manager::EnvExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::EnvExecute >::value();
  }
  static const char* value(const ::node_manager::EnvExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::EnvExecuteResponse> should match 
// service_traits::DataType< ::node_manager::EnvExecute > 
template<>
struct DataType< ::node_manager::EnvExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::node_manager::EnvExecute >::value();
  }
  static const char* value(const ::node_manager::EnvExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_ENVEXECUTE_H
