// Generated by gencpp from file node_manager/EnvExecuteRequest.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_ENVEXECUTEREQUEST_H
#define NODE_MANAGER_MESSAGE_ENVEXECUTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <node_manager/Reaction.h>

namespace node_manager
{
template <class ContainerAllocator>
struct EnvExecuteRequest_
{
  typedef EnvExecuteRequest_<ContainerAllocator> Type;

  EnvExecuteRequest_()
    : reaction()
    , robot_id()  {
    }
  EnvExecuteRequest_(const ContainerAllocator& _alloc)
    : reaction(_alloc)
    , robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::node_manager::Reaction_<ContainerAllocator>  _reaction_type;
  _reaction_type reaction;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_id_type;
  _robot_id_type robot_id;




  typedef boost::shared_ptr< ::node_manager::EnvExecuteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::EnvExecuteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnvExecuteRequest_

typedef ::node_manager::EnvExecuteRequest_<std::allocator<void> > EnvExecuteRequest;

typedef boost::shared_ptr< ::node_manager::EnvExecuteRequest > EnvExecuteRequestPtr;
typedef boost::shared_ptr< ::node_manager::EnvExecuteRequest const> EnvExecuteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::EnvExecuteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_manager': ['/home/artsobes/Documents/Development/ROS/catkin_ws/src/node_manager/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::EnvExecuteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::EnvExecuteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::EnvExecuteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8ce2aa862d8aeb4492c1226ca98bdd9";
  }

  static const char* value(const ::node_manager::EnvExecuteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8ce2aa862d8aeb4ULL;
  static const uint64_t static_value2 = 0x492c1226ca98bdd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/EnvExecuteRequest";
  }

  static const char* value(const ::node_manager::EnvExecuteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Reaction reaction\n\
string robot_id\n\
\n\
================================================================================\n\
MSG: node_manager/Reaction\n\
int64 vx\n\
";
  }

  static const char* value(const ::node_manager::EnvExecuteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reaction);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EnvExecuteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::EnvExecuteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::EnvExecuteRequest_<ContainerAllocator>& v)
  {
    s << indent << "reaction: ";
    s << std::endl;
    Printer< ::node_manager::Reaction_<ContainerAllocator> >::stream(s, indent + "  ", v.reaction);
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_ENVEXECUTEREQUEST_H
