// Generated by gencpp from file node_manager/NumResponse.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_NUMRESPONSE_H
#define NODE_MANAGER_MESSAGE_NUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_manager
{
template <class ContainerAllocator>
struct NumResponse_
{
  typedef NumResponse_<ContainerAllocator> Type;

  NumResponse_()
    : Num(0)  {
    }
  NumResponse_(const ContainerAllocator& _alloc)
    : Num(0)  {
    }



   typedef int64_t _Num_type;
  _Num_type Num;




  typedef boost::shared_ptr< ::node_manager::NumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::NumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NumResponse_

typedef ::node_manager::NumResponse_<std::allocator<void> > NumResponse;

typedef boost::shared_ptr< ::node_manager::NumResponse > NumResponsePtr;
typedef boost::shared_ptr< ::node_manager::NumResponse const> NumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::NumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::NumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::NumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::NumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::NumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::NumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::NumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::NumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::NumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94656e1b849ade935c34cb79b08be4df";
  }

  static const char* value(const ::node_manager::NumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94656e1b849ade93ULL;
  static const uint64_t static_value2 = 0x5c34cb79b08be4dfULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::NumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/NumResponse";
  }

  static const char* value(const ::node_manager::NumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::NumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Num\n\
\n\
";
  }

  static const char* value(const ::node_manager::NumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::NumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::NumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::NumResponse_<ContainerAllocator>& v)
  {
    s << indent << "Num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_NUMRESPONSE_H
