// Generated by gencpp from file node_manager/Reaction.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_REACTION_H
#define NODE_MANAGER_MESSAGE_REACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_manager
{
template <class ContainerAllocator>
struct Reaction_
{
  typedef Reaction_<ContainerAllocator> Type;

  Reaction_()
    : vx(0)  {
    }
  Reaction_(const ContainerAllocator& _alloc)
    : vx(0)  {
  (void)_alloc;
    }



   typedef int64_t _vx_type;
  _vx_type vx;




  typedef boost::shared_ptr< ::node_manager::Reaction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::Reaction_<ContainerAllocator> const> ConstPtr;

}; // struct Reaction_

typedef ::node_manager::Reaction_<std::allocator<void> > Reaction;

typedef boost::shared_ptr< ::node_manager::Reaction > ReactionPtr;
typedef boost::shared_ptr< ::node_manager::Reaction const> ReactionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::Reaction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::Reaction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_manager': ['/home/artsobes/Documents/Development/ROS/catkin_ws/src/node_manager/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::Reaction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::Reaction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::Reaction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::Reaction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::Reaction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::Reaction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::Reaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7167721f8ece6d6a060283246087ac5b";
  }

  static const char* value(const ::node_manager::Reaction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7167721f8ece6d6aULL;
  static const uint64_t static_value2 = 0x060283246087ac5bULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::Reaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/Reaction";
  }

  static const char* value(const ::node_manager::Reaction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::Reaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 vx\n\
";
  }

  static const char* value(const ::node_manager::Reaction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::Reaction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Reaction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::Reaction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::Reaction_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_REACTION_H
