// Generated by gencpp from file node_manager/ReqRequest.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_REQREQUEST_H
#define NODE_MANAGER_MESSAGE_REQREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_manager
{
template <class ContainerAllocator>
struct ReqRequest_
{
  typedef ReqRequest_<ContainerAllocator> Type;

  ReqRequest_()
    : x(0)
    , vx(0)  {
    }
  ReqRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , vx(0)  {
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _vx_type;
  _vx_type vx;




  typedef boost::shared_ptr< ::node_manager::ReqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::ReqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReqRequest_

typedef ::node_manager::ReqRequest_<std::allocator<void> > ReqRequest;

typedef boost::shared_ptr< ::node_manager::ReqRequest > ReqRequestPtr;
typedef boost::shared_ptr< ::node_manager::ReqRequest const> ReqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::ReqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::ReqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::ReqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::ReqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::ReqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::ReqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::ReqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::ReqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::ReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6de8594b8454f49c995c3b44bb95105";
  }

  static const char* value(const ::node_manager::ReqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6de8594b8454f49ULL;
  static const uint64_t static_value2 = 0xc995c3b44bb95105ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::ReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/ReqRequest";
  }

  static const char* value(const ::node_manager::ReqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::ReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 vx\n\
";
  }

  static const char* value(const ::node_manager::ReqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::ReqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.vx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ReqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::ReqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::ReqRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "vx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_REQREQUEST_H
