// Generated by gencpp from file node_manager/ReqResponse.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_REQRESPONSE_H
#define NODE_MANAGER_MESSAGE_REQRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_manager
{
template <class ContainerAllocator>
struct ReqResponse_
{
  typedef ReqResponse_<ContainerAllocator> Type;

  ReqResponse_()
    : x(0)  {
    }
  ReqResponse_(const ContainerAllocator& _alloc)
    : x(0)  {
    }



   typedef int64_t _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::node_manager::ReqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::ReqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReqResponse_

typedef ::node_manager::ReqResponse_<std::allocator<void> > ReqResponse;

typedef boost::shared_ptr< ::node_manager::ReqResponse > ReqResponsePtr;
typedef boost::shared_ptr< ::node_manager::ReqResponse const> ReqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::ReqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::ReqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::ReqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::ReqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::ReqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::ReqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::ReqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::ReqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::ReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b429044e1360891965aa67e074722c0e";
  }

  static const char* value(const ::node_manager::ReqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb429044e13608919ULL;
  static const uint64_t static_value2 = 0x65aa67e074722c0eULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::ReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/ReqResponse";
  }

  static const char* value(const ::node_manager::ReqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::ReqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
\n\
";
  }

  static const char* value(const ::node_manager::ReqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::ReqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ReqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::ReqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::ReqResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_REQRESPONSE_H
