// Generated by gencpp from file node_manager/RNode.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_RNODE_H
#define NODE_MANAGER_MESSAGE_RNODE_H

#include <ros/service_traits.h>


#include <node_manager/RNodeRequest.h>
#include <node_manager/RNodeResponse.h>


namespace node_manager
{

struct RNode
{

typedef RNodeRequest Request;
typedef RNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RNode
} // namespace node_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_manager::RNode > {
  static const char* value()
  {
    return "09fd118bc15393e954239c8a0eb51ac3";
  }

  static const char* value(const ::node_manager::RNode&) { return value(); }
};

template<>
struct DataType< ::node_manager::RNode > {
  static const char* value()
  {
    return "node_manager/RNode";
  }

  static const char* value(const ::node_manager::RNode&) { return value(); }
};


// service_traits::MD5Sum< ::node_manager::RNodeRequest> should match 
// service_traits::MD5Sum< ::node_manager::RNode > 
template<>
struct MD5Sum< ::node_manager::RNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::RNode >::value();
  }
  static const char* value(const ::node_manager::RNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::RNodeRequest> should match 
// service_traits::DataType< ::node_manager::RNode > 
template<>
struct DataType< ::node_manager::RNodeRequest>
{
  static const char* value()
  {
    return DataType< ::node_manager::RNode >::value();
  }
  static const char* value(const ::node_manager::RNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_manager::RNodeResponse> should match 
// service_traits::MD5Sum< ::node_manager::RNode > 
template<>
struct MD5Sum< ::node_manager::RNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::RNode >::value();
  }
  static const char* value(const ::node_manager::RNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::RNodeResponse> should match 
// service_traits::DataType< ::node_manager::RNode > 
template<>
struct DataType< ::node_manager::RNodeResponse>
{
  static const char* value()
  {
    return DataType< ::node_manager::RNode >::value();
  }
  static const char* value(const ::node_manager::RNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_RNODE_H
