// Generated by gencpp from file node_manager/WorldIdsResponse.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_WORLDIDSRESPONSE_H
#define NODE_MANAGER_MESSAGE_WORLDIDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_manager
{
template <class ContainerAllocator>
struct WorldIdsResponse_
{
  typedef WorldIdsResponse_<ContainerAllocator> Type;

  WorldIdsResponse_()
    : ids()  {
    }
  WorldIdsResponse_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _ids_type;
  _ids_type ids;




  typedef boost::shared_ptr< ::node_manager::WorldIdsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_manager::WorldIdsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WorldIdsResponse_

typedef ::node_manager::WorldIdsResponse_<std::allocator<void> > WorldIdsResponse;

typedef boost::shared_ptr< ::node_manager::WorldIdsResponse > WorldIdsResponsePtr;
typedef boost::shared_ptr< ::node_manager::WorldIdsResponse const> WorldIdsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_manager::WorldIdsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_manager::WorldIdsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_manager': ['/home/artsobes/Documents/Development/ROS/catkin_ws/src/node_manager/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_manager::WorldIdsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_manager::WorldIdsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_manager::WorldIdsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31314a1125a2ca69ddc92cdc117c989c";
  }

  static const char* value(const ::node_manager::WorldIdsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31314a1125a2ca69ULL;
  static const uint64_t static_value2 = 0xddc92cdc117c989cULL;
};

template<class ContainerAllocator>
struct DataType< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_manager/WorldIdsResponse";
  }

  static const char* value(const ::node_manager::WorldIdsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] ids\n\
\n\
";
  }

  static const char* value(const ::node_manager::WorldIdsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WorldIdsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_manager::WorldIdsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_manager::WorldIdsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_WORLDIDSRESPONSE_H
