// Generated by gencpp from file node_manager/WorldIds.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_WORLDIDS_H
#define NODE_MANAGER_MESSAGE_WORLDIDS_H

#include <ros/service_traits.h>


#include <node_manager/WorldIdsRequest.h>
#include <node_manager/WorldIdsResponse.h>


namespace node_manager
{

struct WorldIds
{

typedef WorldIdsRequest Request;
typedef WorldIdsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WorldIds
} // namespace node_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_manager::WorldIds > {
  static const char* value()
  {
    return "31314a1125a2ca69ddc92cdc117c989c";
  }

  static const char* value(const ::node_manager::WorldIds&) { return value(); }
};

template<>
struct DataType< ::node_manager::WorldIds > {
  static const char* value()
  {
    return "node_manager/WorldIds";
  }

  static const char* value(const ::node_manager::WorldIds&) { return value(); }
};


// service_traits::MD5Sum< ::node_manager::WorldIdsRequest> should match 
// service_traits::MD5Sum< ::node_manager::WorldIds > 
template<>
struct MD5Sum< ::node_manager::WorldIdsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::WorldIds >::value();
  }
  static const char* value(const ::node_manager::WorldIdsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::WorldIdsRequest> should match 
// service_traits::DataType< ::node_manager::WorldIds > 
template<>
struct DataType< ::node_manager::WorldIdsRequest>
{
  static const char* value()
  {
    return DataType< ::node_manager::WorldIds >::value();
  }
  static const char* value(const ::node_manager::WorldIdsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_manager::WorldIdsResponse> should match 
// service_traits::MD5Sum< ::node_manager::WorldIds > 
template<>
struct MD5Sum< ::node_manager::WorldIdsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::WorldIds >::value();
  }
  static const char* value(const ::node_manager::WorldIdsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::WorldIdsResponse> should match 
// service_traits::DataType< ::node_manager::WorldIds > 
template<>
struct DataType< ::node_manager::WorldIdsResponse>
{
  static const char* value()
  {
    return DataType< ::node_manager::WorldIds >::value();
  }
  static const char* value(const ::node_manager::WorldIdsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_WORLDIDS_H
