(cl:defpackage node_manager-srv
  (:use )
  (:export
   "WORLDIDS"
   "<WORLDIDS-REQUEST>"
   "WORLDIDS-REQUEST"
   "<WORLDIDS-RESPONSE>"
   "WORLDIDS-RESPONSE"
   "ENVEXECUTE"
   "<ENVEXECUTE-REQUEST>"
   "ENVEXECUTE-REQUEST"
   "<ENVEXECUTE-RESPONSE>"
   "ENVEXECUTE-RESPONSE"
   "WORLDPROPERTIES"
   "<WORLDPROPERTIES-REQUEST>"
   "WORLDPROPERTIES-REQUEST"
   "<WORLDPROPERTIES-RESPONSE>"
   "WORLDPROPERTIES-RESPONSE"
   "RNODE"
   "<RNODE-REQUEST>"
   "RNODE-REQUEST"
   "<RNODE-RESPONSE>"
   "RNODE-RESPONSE"
  ))

